### ISSUE TITLE
Kenlm error while running bash scripts/prepare_model.sh config/data.en.config

### ISSUE THREAD

**Issue by sabahahmed1** [pmichel31415/mtnt#6]
Hello, there!

I am trying to reproduce the findings from your paper for a school project using Google Colab.

After installing packages including Kenlm, when I type:

> bash scripts/prepare_model.sh config/data.en.config

I keep getting the following error:

> Traceback (most recent call last): File "kenlm.pyx", line 139, in kenlm.Model.init RuntimeError: util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'. No such file or directory while opening /content/mtnt/models/corpus.en.1000.bpe.lm.5.bin
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "scripts/eval_kenlm.py", line 14, in model = kenlm.Model(model_file) File "kenlm.pyx", line 142, in kenlm.Model.init OSError: Cannot read model 'models/corpus.en.1000.bpe.lm.5.bin' (util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'. No such file or directory while opening /content/mtnt/models/corpus.en.1000.bpe.lm.5.bin)

Please advise. I would appreciate your input. Thanks

**Comment by vcyrot** [comment]
> Hello, there!
> 
> I am trying to reproduce the findings from your paper for a school project using Google Colab.
> 
> After installing packages including Kenlm, when I type:
> 
> > bash scripts/prepare_model.sh config/data.en.config
> 
> I keep getting the following error:
> 
> > Traceback (most recent call last): File "kenlm.pyx", line 139, in kenlm.Model.init RuntimeError: util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'. No such file or directory while opening /content/mtnt/models/corpus.en.1000.bpe.lm.5.bin
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "scripts/eval_kenlm.py", line 14, in model = kenlm.Model(model_file) File "kenlm.pyx", line 142, in kenlm.Model.init OSError: Cannot read model 'models/corpus.en.1000.bpe.lm.5.bin' (util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'. No such file or directory while opening /content/mtnt/models/corpus.en.1000.bpe.lm.5.bin)
> 
> Please advise. I would appreciate your input. Thanks

I'm also facing the same problem...
